### ISSUE TITLE
Missing application examples

### ISSUE THREAD

**Issue by junmaqiang** [fynelabs/fyneselfupdate#9]
## Being able to show progress and UI interaction would be better

**Comment by andydotxyz** [comment]
The documentation shows how it can be used.

This will add the UI interaction and progress display automatically.

**Comment by sevpants** [comment]
Would also like to see some other examples. I've added the example from the readme to my existing app with my public key from selfupdatectl and uploaded the binary to my s3 (and made the url public in case that was necessary). I updated the httpSource with my s3url and I've made it so that my local is a prior version of the s3 release. 

I get the application update ui but when I click yes nothing happens. Not entirely sure what I'm missing. For reference I call the below func at the top of my main func. I've double checked that the s3 bucket it public and am able to access it as a guest.

```func enable(a fyne.App, w fyne.Window) {
	publicKey := ed25519.PublicKey(mypublickey}
	log.Println("Public key:", publicKey)
	// The public key above matches the signature of the below file served by our CDN
	httpSource := selfupdate.NewHTTPSource(nil, "https://example.s3.s3regionexample.amazonaws.com/program-name-{{.OS}}-{{.Arch}}{{.Ext}}")
	log.Println("HTTP source:", httpSource)
	config := fyneselfupdate.NewConfigWithTimeout(a, w, time.Minute, httpSource, selfupdate.Schedule{FetchOnStart: true, Interval: time.Minute * time.Duration(1)}, publicKey)
	log.Println("Config:", config)
	_, err := selfupdate.Manage(config)
	if err != nil {
		fyne.LogError("Error while setting up update manager: ", err)
		return
	}
	log.Println("Update manager set up successfully??")
}

**Comment by andydotxyz** [comment]
It sounds like you are looking to debug rather than to get more code. Why not set `LogError` or `LogInfo` as described in the `FyneLabs/selfupdate` library that this wraps... it may provide clues.

**Comment by junmaqiang** [comment]
> 听起来您正在寻找调试而不是获取更多代码。为什么不设置`LogError`或`LogInfo`按照它包装的库中的描述`FyneLabs/selfupdate`...它可能会提供线索。

Yes, I'd love to shed some light on the upgrade process and possibly optimize it

**Comment by junmaqiang** [comment]
> 还想看看其他一些例子。我已使用 selfupdatectl 中的公钥将自述文件中的示例添加到我现有的应用程序中，并将二进制文件上传到我的 s3（并在必要时公开 URL）。我用 s3url 更新了 httpSource，这样我的本地版本就是 s3 版本的早期版本。
> 
> 我收到应用程序更新用户界面，但当我单击“是”时，什么也没有发生。不完全确定我错过了什么。作为参考，我在主函数顶部调用以下函数。我已经仔细检查了 s3 存储桶是否公开，并且能够以访客身份访问它。
> 
> ```
> 	publicKey := ed25519.PublicKey(mypublickey}
> 	log.Println("Public key:", publicKey)
> 	// The public key above matches the signature of the below file served by our CDN
> 	httpSource := selfupdate.NewHTTPSource(nil, "https://example.s3.s3regionexample.amazonaws.com/program-name-{{.OS}}-{{.Arch}}{{.Ext}}")
> 	log.Println("HTTP source:", httpSource)
> 	config := fyneselfupdate.NewConfigWithTimeout(a, w, time.Minute, httpSource, selfupdate.Schedule{FetchOnStart: true, Interval: time.Minute * time.Duration(1)}, publicKey)
> 	log.Println("Config:", config)
> 	_, err := selfupdate.Manage(config)
> 	if err != nil {
> 		fyne.LogError("Error while setting up update manager: ", err)
> 		return
> 	}
> 	log.Println("Update manager set up successfully??")
> }
> ```

I agree, the upgrade process needs to be open and transparent, not a secretive process

**Comment by andydotxyz** [comment]
This project is completely open source, there is nothing secretive at all.
It was implemented by other teams following the documentation.

To know why it is not working for you requires debugging - which is why I recommend turning on the documented logging features.

**Comment by junmaqiang** [comment]
> 这个项目是完全开源的，没有什么秘密可言。 它是由其他团队按照文档实施的。
> 
> 要知道为什么它不适合您需要调试 - 这就是为什么我建议打开记录的日志记录功能。

Sorry, it may be due to inaccurate translation. What I meant was that I wanted to see the upgrade process through the log. How to turn it on? I have set it up but nothing seems to happen

```
	// ④
	update.LogDebug = func(s string, i ...interface{}) {
		logs.L.Debugln(s)
	}
	update.LogError = func(s string, i ...interface{}) {
		logs.L.Errorln(s)
	}
	update.LogInfo = func(s string, i ...interface{}) {
		logs.L.Infoln(s)
	}
	// ⑤
	_, err := update.Manage(config)
	if err != nil {
		fmt.Println("err: ", err)
		return
	}

```
